<x-guest-layout>
    <section id="sales-main">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 col-md-12 d-flex text-justify">
                    <div class="sales-box-content" style="margin-top: 20px !important;">
                        <h2>ACCEPTANCE OF TERMS OF SERVICE</h2>
                        <p>These terms and conditions form a contract between you and Greymetre Consultants Pvt. Ltd. (Greymetre) in respect of the Service. For your own benefit and protection, please read the terms and conditions set out herein carefully before you register for and use the Service of Greymetre.</p>
                        <p>By registering for and/or by using the Service through your Mobile device, You confirm that you have read, understood and accepted these Terms and Conditions and are legally bound by these Terms and Conditions, and all other terms and conditions that govern Greymetre online Website, as may be amended from time to time (collectively, the "Terms and Conditions") and they will continue to apply every time you use the Service. If you do not accept any of the Terms & Conditions stated herein do not use the Service.</p>
                        <p>The functionality and Information available through this Service are more limited than the functionality and information available through Greymetre Website. TERMS & CONDITIONS<br>In these terms and conditions, "you" and "your" mean the individual who is using the Service.</p>
                        <h6 class="pt-4">1. GENERAL</h6>
                        <p>By installing the Application (Software), provided by Greymetre to offer services related to Greymetre, Greymetre's services and any upgrades from time to time and any other software or documentation which enables the use of the Application, you agree to be bound by these terms of use ("terms"). Please review them carefully before installation and/or acceptance.</p>
                        <h6 class="pt-4">2. LIMIT TO USERS</h6>
                        <p>The Application, containing information on Greymetre, its products, services, offers, promotions etc. is intended for use only in India. The Application allows you to access certain functionality available on Greymetre website. Such access will be governed by Greymetre Website Terms of Use. <br>
                            Any personal information you supply to Greymetre while using the Application will be used by Greymetre in accordance with the Privacy Policy available in Greymetre Website.</p>
                        <h6 class="pt-4">3. CONDITIONS OF USE:</h6>
                        <p>You understand, acknowledge and agree that:<br>
                            You will only use the Service and the Application, currently made available to you free of charge, solely and exclusively for your own personal, private, non-commercial use and on registered mobile devices that are authorized by Greymetre, belonging to you; Greymetre reserves the right to amend or withdraw the Application or change for the application or service provided to you in accordance with the terms at any time for any reason.<br>
                            The terms of agreement with your respective mobile network provider('Mobile Provider') will continue to apply when using the Application and Mobile Provider may charge to access to network connection services for the duration of the connection with accessing the Application or any such third party charges as may arise. You accept responsibility for any such charges that arise <br>
                            You will at all times comply with (and your use of the Service and the Application will at all times be in compliance with) the Terms and Conditions, all applicable laws, rules and regulations, and you will not allow any other party to use the Service or the Application for or in connection with any illegal purpose or activity.<br>
                            Use of the Application including the Service is at your own risk and you are solely responsible for the use of any data, information or services obtained through the use of the Service; <br>
                            The Service is provided as a convenience to you. The information accessible through the Service is more limited than the information available through the Greymetre website; and
                            In the event that you fail to comply with the Terms and Conditions or your account with Greymetre is closed, all rights granted to you in relation to the Application and the Service shall immediately come to an end and you will immediately destroy all copies of the Application.</p>
                        <h6 class="pt-4">4. RESTRICTIONS ON USE:</h6>
                        <p>You are hereby granted a limited, non-exclusive, non-transferable, non-assignable license to view and use the Application (which shall include future updates made available to you from time to time, provided you understand that such updates may be subject to additional terms in respect of which you will be notified at the time such update is made available) to access from your mobile device,.<br>
                            You will not:<br>
                            Alter, modify, adapt or translate the whole or any part of the Application, or any other computer software made accessible to you or otherwise and use the Service, or perform maintenance on the Application,<br>
                            Copy, reproduce, duplicate, compile, disseminate, reverse engineer, disassemble, decompile, transfer, exchange disable any features, or otherwise derive the source code for the Application, or any component of the Application or the Service whatsoever, in whole or in part;<br>
                            Merging the Application or any component thereof into any other programs or create derivative works based on any component of the Application;<br>
                            Use the Application in whole or in part or any confidential information relating thereto to create software that is functionally equivalent to the Application or any part thereof;<br>
                            License, sublicense, sell, disseminate, broadcast, transmit, or otherwise distribute the Application or the Service in any form or by any means, or otherwise transfer, assign, manipulate, or grant any rights of use or any other rights in respect of the Application or the Service, or any part thereof, or the information contained therein, to any other party;<br>
                            Remove or tamper with any proprietary notices or labels, including copyright notices or data source attributions, attached to or contained within the Application or the Service;<br>
                            Use the Application or the Service in any way that may lead to the encouragement, procurement or carrying out of any unlawful or criminal activity or which may cause any harm or injury to any person;<br>
                            Cause damage to any of the websites, servers, systems or equipment used in the provision of the Service by Greymetre or any other third party, and you may not access or attempt to access any user data or to penetrate any of the security measures relating to the Service; and will in all cases indemnify and hold harmless Greymetre from any and all Claims in respect thereof.</p>
                        <h6 class="pt-4">5. ACCESS </h6>
                        <p>You are solely responsible for all information entered through or electronically transmitted to us through the Service using your sign-on password, and/or access code, and you accept that all such data transmissions are undertaken at your own risk. Greymetre is not liable for any error made by you in entering any details or providing any orders and you agree that Greymetre shall be entitled to rely upon orders received from you using your sign-on password. You must always keep confidential, and will take all necessary precautions to ensure the confidentiality and security of all of your access credentials, and will take all necessary precautions to prevent unauthorized access to the Service.</p>
                        <h6 class="pt-4">6. AVAILABILITY </h6>
                        <p>6.1. This Application is available to a compatible mobile telephone or handheld mobile devices viz., Android OS Operating Systems devices running Android 6.0 & above , with internet access. The version of the Application software may be upgraded from time to time to add support for new functions and services. Greymetre will use reasonable efforts to make the Application available at all times. However you acknowledge the Application is provided over the internet and mobile networks and so the quality and availability of the Application may be affected by factors outside Greymetre reasonable control.<br>
                            6.2. Greymetre, and third party, do not accept any responsibility whatsoever for unavailability of the Application, or any difficulty or inability to download or access content or any other communication system failure which may result in the Application being unavailable.<br>
                            6.3. Greymetre will not be responsible for any support or maintenance for the Application.</p>
                        <h6 class="pt-4">7. PROPRIETARY RIGHTS AND LICENCE </h6>
                        <p>7.1 All ownership, rights, title, interest, database rights and other intellectual property rights of any nature in the Application together with the underlying software code, all information, data, text, software, music, video clips, animation, sound, photographs, images, pictures, graphics, messages, tags, or other materials and the Service, including, but not limited to, all trade names and any and all copyright, patents, trademarks, and service marks relating thereto, are and shall remain the property of Greymetre and/or its licensors and nothing herein shall be construed as granting any rights therein to you. You acquire no right, title or interest whatsoever in or to the Application or the Service, as either of them exist now or in the future.<br>
                            All intellectual property rights owned by third parties in any Information provided by third parties shall at all times remain the property of such third parties. Your use of such Information is subject to the terms and conditions of each applicable third party. Greymetre accepts no liability for any Information provided by third parties and make no representations or warranties that such Information will be accurate or timely.<br>
                            7.2. Greymetre hereby grants you a worldwide, non-exclusive, royalty-free revocable licence to use the Application for your personal use in accordance with these terms.</p>
                        <h6 class="pt-4">8. TERMINATION AND MODIFICATION</h6>
                        <p>You understand, acknowledge and agree that Greymetre may in its sole discretion, at any time:<br>
                            Modify any part of the Service and/or change the terms and conditions upon which the Service is provided to you,<br>
                            Discontinue temporarily or permanently, or terminate the Service in part or in its entirety,<br>
                            Without notice terminate or otherwise limit your access to the Service at any time for any reason, including, without limiting the generality of the foregoing, in the event that Greymetre believes that you are in breach of or have failed to comply with any of the Terms and Conditions or in the event that Greymetre believes that you are using the Service illegally, fraudulently or improperly, in which event all rights granted to you hereunder shall immediately cease without notice to you.<br>
                            Greymetre shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.<br>
                            Upon any termination, (a) the rights and licenses granted to you herein shall terminate; (b) you must cease all use of the Software;</p>
                        <h6 class="pt-4">9. LIMITATION OF LIABILITY</h6>
                        <p>9.1 You acknowledge that the Service and the Application utilize complex computer and telecommunications networks and that, as such, continued, uninterrupted and error free access to the Service and/or the Application cannot be guaranteed. In the light of the foregoing, Greymetre or any third party, officers, directors, employees, representatives, successors and assigns shall not be liable in any way for any loss or damage, direct or indirect, which may arise, from any outage, interruption, discontinuation or delay in the Service or the Application or any part thereof or any error contained therein, or from any other non-performance, defective performance or late performance due to any cause whatsoever, including errors due to malfunction of equipment, programs or operations of Greymetre or any third parties, or negligence of Greymetre or any third party.<br>
                            9.1 In no event will Greymetre be liable for any direct, indirect, special, punitive, exemplary or consequential losses or damages of whatsoever kind arising out of your use or inability to use or access or inability to access to the Service or Application, including loss of profit or the like whether or not in the contemplation of the parties, whether based on breach of contract, tort (including negligence) or otherwise.<br>
                            9.2. Greymetre is not liable to you for any damage or alteration to your equipment including but not limited to computer equipment, handheld device or mobile telephones as a result of the installation or use of the Application.</p>
                        <h6 class="pt-4">10. DISCLAIMER OF WARRANTIES</h6>
                        <p>10.1 The Service may be delayed, unavailable, not delivered and/or inaccurate from time to time due to a variety of factors, including technical reasons, for planned or unplanned maintenance or downtime, for editorial amendments or for any other reason. The Service may be adversely affected by the performance of and any outages on mobile device networks, or when you are not in an area of mobile coverage, or other factors beyond the control of Greymetre or any third party, and neither Greymetre nor any third party will be liable therefor.<br>
                            10.2 The Service and the Application are provided �as is� and �as available�, and all warranties, representations and guarantees, express or implied, are hereby disclaimed. Without limiting the generality of the foregoing, any and all warranties of merchantability, fitness for a particular purpose, suitability, reliability, accuracy, performance, compatibility or non-infringement, or that the Service or the Application will be free from defects, errors, viruses, worms or harmful programs, or be of a satisfactory quality, are hereby expressly disclaimed or that access to the Application will be uninterrupted or error-free.<br>
                            10.3 Neither Greymetre nor any third party provider makes any warranty, representation or guarantee as to the accessibility, reliability, communication links, accuracy, truth, timeliness, or completeness of any Information or data furnished through the Service.</p>
                        <h6 class="pt-4">11. INDEMNIFICATION</h6>
                        <p>You agree to defend, indemnify and hold Greymetre, its Affiliates, officers, directors, employees, representatives, successors and assigns, harmless from any and all claims, liabilities, costs and expenses, including reasonable attorneys' fees, arising in any way from your use or misuse of the Application or Services or any violation of these Terms and Conditions by you.</p>
                        <h6 class="pt-4">12. INDEPENDENT CONTRACTORS</h6>
                        <p>You acknowledge that the usage of this Website by you does not constitute a joint venture, partnership, employment or agency relationship between you and Greymetre. You agree not to hold yourself as a representative, agent or employee of Greymetre and Greymetre shall not be liable for any representation, act or omission by you.</p>
                        <h6 class="pt-4">13. LAWS AND JURISDICTION</h6>
                        <p>The interpretation of these terms and conditions shall be construed in accordance with and governed by the laws of India. Any disputes arising under or in connection with the use of Application or Service or the Terms shall be subject to the exclusive jurisdiction of the Courts in New Delhi, India.</p>
                        <h6 class="pt-4">14. MISCELLANEOUS</h6>
                        <p>If any part of these Terms and Conditions is held invalid or unenforceable under any applicable law, the validity or enforceability of the remaining provisions contained herein shall not be affected in any manner whatsoever, and any such invalid or unenforceable provision shall be deemed to be severable and ineffective only to the extent necessary to render the remaining portions of these terms and conditions valid and enforceable. The section titles in these Terms and Conditions are for convenience only, and have no legal or contractual effect. You shall not transfer, assign, sublicense nor pledge in any manner whatsoever, any of your rights or obligations under these Terms and Conditions. Greymetre may transfer, assign sublicense or pledge in any manner whatsoever, any of its rights and obligations under these Terms and Conditions to a subsidiary, affiliate or to any third party whatsoever, without notifying you or receiving your consent.</p>
                        <h6 class="pt-4">15. LOCATION</h6>
                        <p>Our app collects location data to enable features such as real-time tracking, geofencing, and background location services — even when the app is closed or not in use. This data is used to: <br>
                            Track user movement (for [attendance/workforce/travel/delivery] tracking)
                            Detect geofence entry/exit
                            Provide navigation or route information
                            We do not share your location data with any third parties without your explicit consent. <br>
                            Location data is collected via foreground and background services, as required for core functionality.
                            You can choose to disable location access at any time in your device settings.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</x-guest-layout>